
const colorMap: Record<string, string> = {
    // Màu cơ bản
    'đỏ': 'red',
    'xanh': 'blue',
    'vàng': 'yellow',
    'trắng': 'white',
    'đen': 'black',
    'xám': 'gray',
    'xanh lá': 'green',
    'hồng': 'pink',
    'tím': 'purple',
    'nâu': 'brown',
    'cam': 'orange',
    'be': 'beige',
    'vàng chanh': 'lemon',
    'màu mận': 'plum',
    'xanh da trời': 'skyblue',
    'xanh dương': 'navy',
    'xanh lục': 'teal',
    'xanh lam': 'cyan',
    'vàng đậm': 'gold',
    'bạc': 'silver',
    'trắng ngà': 'ivory',
    'hồng nhạt': 'lightpink',
    'hồng đậm': 'deeppink',

    // Các biến thể của màu sắc
    'đỏ đậm': 'darkred',
    'đỏ nhạt': 'lightcoral',
    'xanh lá đậm': 'darkgreen',
    'xanh lá nhạt': 'lightgreen',
    'xanh da trời đậm': 'darkblue',
    'xanh da trời nhạt': 'lightskyblue',

    'vàng nhạt': 'lightyellow',
    'nâu đậm': 'saddlebrown',
    'nâu nhạt': 'sandybrown',
    'cam đậm': 'darkorange',
    'cam nhạt': 'peachpuff',
    'xám đậm': 'dimgray',
    'xám nhạt': 'lightgray',
    'trắng sữa': 'seashell',
    'trắng bạc': 'ghostwhite',

    // Các màu theo phong cách thời trang và mỹ phẩm
    'màu rượu vang': 'wine',
    'màu cafe': 'coffee',
    'màu mực': 'midnightblue',
    'màu hạt dẻ': 'chestnut',
    'màu thạch anh': 'amethyst',
    'màu xám đá': 'slategray',
    'màu than': 'charcoal',
    'màu cát': 'sand',
    'màu hoa hồng': 'rose',
    'màu nắng': 'sunflower',
    'màu gạch': 'brickred',
    'màu lúa mì': 'wheat',
    'màu xám bạc': 'silvergray',
    'màu bùn': 'mud',
    'màu xanh bạc hà': 'mint',
    'màu trà xanh': 'matcha',
    'màu mơ': 'peach',
    'màu lá phong': 'maple',

    // Các màu sắc khác
    'màu ngọc bích': 'turquoise',
    'màu ngọc lục bảo': 'emerald',
    'màu ngọc bích xanh': 'aquamarine',
    'màu hoa anh đào': 'cherryblossom',
    'màu bạc hà': 'honeydew',
    'màu hạt dẻ nướng': 'roastedchestnut',
    'màu đậu phộng': 'peanut',
    'màu cẩm thạch': 'marble',
    'màu cánh sen': 'lotus',
    'màu băng': 'iceblue',
    'màu lá cây': 'olive',
    'màu hoa violet': 'violet',
    'màu kim cương': 'diamond',
    'màu xà cừ': 'pearl',
    'màu mật ong': 'honey',
} as const;

export default colorMap;
